# Generated by Django 5.2.5 on 2025-09-03 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id_colegio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_dane', models.CharField(help_text='Código DANE de la institución', max_length=225, unique=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('num_estudiantes', models.IntegerField(default=0)),
                ('num_docentes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=255)),
                ('grado', models.CharField(max_length=255)),
                ('colegio', models.ForeignKey(db_column='id_colegio', on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='gestion.colegio')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=True, help_text='True = presente, False = ausente')),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion.estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('estudiante', 'fecha')},
            },
        ),
    ]
